name: Test & Deploy

# Specify deployment intialisation.
on:
    push:
        branches:
            - main

jobs:
    # Tests
    # Deploy
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Use Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Application Requirements
              run: make requirements

            - name: Implement AWS Credentials & Create ECR Repository
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ secrets.AWS_REGION }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            - name: Create ECR 
              run: aws ecr create-repository --repository-name my-docker-repo

            - name: Deploy Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Terraform Init
              working-directory: terraform
              run: terraform init

            - name: Terraform Plan
              working-directory: terraform
              run: terraform plan

            - name: Terraform Apply
              working-directory: terraform
              run: terraform apply -auto-approve

            # - name: Terraform Destroy
            #   working-directory: terraform
            #   run: terraform destroy -auto-approve

            # - name: Destroy ECR
            #   run: aws ecr delete-repository --repository-name my-docker-repo --force
             

  