name: Test & Deploy

# Specify deployment intialisation.
on:
    push:
        branches:
            - main

jobs:
    # Tests
    # Deploy
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Use Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Application Requirements
              run: make requirements

            - name: Implement AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ secrets.AWS_REGION }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            
            - name: Deploy Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              run: terraform plan

            - name: Terraform apply
              run: terraform apply -auto-approve


            
